import { StyleSheet } from "react-native";
import { pokemonDetailsTheme } from "./pokemon-details-theme";

export const pokemonDetailsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: pokemonDetailsTheme.background,
  },
  content: {
    padding: 16,
    paddingBottom: 28,
    gap: 16,
  },
  centeredState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    backgroundColor: pokemonDetailsTheme.background,
  },
  stateCopy: {
    marginTop: 12,
    fontSize: 16,
    color: pokemonDetailsTheme.textSecondary,
  },
  errorTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: pokemonDetailsTheme.error,
    marginBottom: 10,
  },
  errorCopy: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    color: pokemonDetailsTheme.errorMuted,
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: pokemonDetailsTheme.action,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
  },
  retryButtonLabel: {
    color: pokemonDetailsTheme.white,
    fontSize: 15,
    fontWeight: "700",
  },
  heroCard: {
    backgroundColor: pokemonDetailsTheme.heroBackground,
    borderRadius: 28,
    padding: 20,
    overflow: "hidden",
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
  },
  pokemonNumber: {
    fontSize: 14,
    fontWeight: "700",
    color: pokemonDetailsTheme.textOnDarkMuted,
    marginBottom: 8,
  },
  pokemonName: {
    fontSize: 34,
    fontWeight: "900",
    color: pokemonDetailsTheme.textOnDark,
  },
  favoriteButton: {
    alignSelf: "flex-start",
    marginTop: 14,
    width: 44,
    height: 44,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  favoriteButtonActive: {
    backgroundColor: "#F59E0B",
    borderColor: "#FCD34D",
  },
  favoriteButtonLabel: {
    fontSize: 24,
    fontWeight: "800",
    color: pokemonDetailsTheme.textOnDark,
    lineHeight: 26,
  },
  typeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
    maxWidth: 160,
  },
  typeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  typeBadgeLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  artworkWrap: {
    height: 250,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
  },
  artworkGlow: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: pokemonDetailsTheme.heroGlow,
    opacity: 0.25,
  },
  artwork: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  artworkFallback: {
    justifyContent: "center",
    alignItems: "center",
  },
  artworkFallbackLabel: {
    fontSize: 64,
    fontWeight: "900",
    color: pokemonDetailsTheme.textOnDark,
  },
  helperCopy: {
    fontSize: 14,
    lineHeight: 21,
    color: pokemonDetailsTheme.textMuted,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: pokemonDetailsTheme.surface,
    borderRadius: 22,
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: pokemonDetailsTheme.border,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: pokemonDetailsTheme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 18,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  sectionCard: {
    backgroundColor: pokemonDetailsTheme.surface,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: pokemonDetailsTheme.border,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
    marginBottom: 14,
  },
  abilityRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  abilityChip: {
    backgroundColor: pokemonDetailsTheme.surfaceMuted,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
  },
  abilityLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: pokemonDetailsTheme.textSecondary,
  },
  statsList: {
    gap: 14,
  },
  statRow: {
    gap: 8,
  },
  statHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: pokemonDetailsTheme.textSecondary,
  },
  statValue: {
    fontSize: 15,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  statTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: pokemonDetailsTheme.surfaceMuted,
    overflow: "hidden",
  },
  statFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: pokemonDetailsTheme.heroAccent,
  },
  modalTrigger: {
    backgroundColor: pokemonDetailsTheme.surface,
    borderWidth: 1,
    borderColor: pokemonDetailsTheme.border,
    borderRadius: 24,
    padding: 18,
    gap: 8,
  },
  modalTriggerEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    color: pokemonDetailsTheme.action,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  modalTriggerTitle: {
    fontSize: 21,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  modalTriggerCopy: {
    fontSize: 15,
    lineHeight: 22,
    color: pokemonDetailsTheme.textSecondary,
  },
  modalTriggerAction: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: "800",
    color: pokemonDetailsTheme.action,
  },
});

export const pokemonInsightsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: pokemonDetailsTheme.background,
  },
  content: {
    padding: 20,
    paddingBottom: 32,
    gap: 16,
  },
  headerCard: {
    backgroundColor: pokemonDetailsTheme.heroBackground,
    borderRadius: 28,
    padding: 20,
    gap: 12,
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute",
    right: -24,
    top: -18,
    width: 140,
    height: 140,
    borderRadius: 999,
    backgroundColor: pokemonDetailsTheme.heroGlow,
    opacity: 0.2,
  },
  headerEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    color: pokemonDetailsTheme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: "900",
    color: pokemonDetailsTheme.textOnDark,
  },
  headerCopy: {
    fontSize: 15,
    lineHeight: 22,
    color: pokemonDetailsTheme.textOnDarkMuted,
  },
  spotlightRow: {
    flexDirection: "row",
    gap: 12,
  },
  spotlightCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 18,
    padding: 14,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  spotlightLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: pokemonDetailsTheme.textOnDarkMuted,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  spotlightValue: {
    fontSize: 18,
    fontWeight: "900",
    color: pokemonDetailsTheme.textOnDark,
  },
  card: {
    backgroundColor: pokemonDetailsTheme.surface,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: pokemonDetailsTheme.border,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  sectionCopy: {
    fontSize: 14,
    lineHeight: 21,
    color: pokemonDetailsTheme.textMuted,
  },
  flavorText: {
    fontSize: 16,
    lineHeight: 24,
    color: pokemonDetailsTheme.textSecondary,
  },
  splitRow: {
    flexDirection: "row",
    gap: 12,
  },
  splitCard: {
    flex: 1,
    backgroundColor: pokemonDetailsTheme.surfaceMuted,
    borderRadius: 20,
    padding: 16,
    gap: 8,
  },
  splitLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: pokemonDetailsTheme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  splitValue: {
    fontSize: 18,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  factGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  factCard: {
    width: "48%",
    backgroundColor: pokemonDetailsTheme.surfaceMuted,
    borderRadius: 20,
    padding: 14,
    gap: 6,
  },
  factLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: pokemonDetailsTheme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  factValue: {
    fontSize: 17,
    fontWeight: "800",
    color: pokemonDetailsTheme.textPrimary,
  },
  accentDivider: {
    height: 1,
    backgroundColor: pokemonDetailsTheme.border,
    marginVertical: 2,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  chip: {
    backgroundColor: pokemonDetailsTheme.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  chipLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: pokemonDetailsTheme.textSecondary,
  },
  centeredState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    backgroundColor: pokemonDetailsTheme.background,
  },
  stateCopy: {
    marginTop: 12,
    fontSize: 16,
    color: pokemonDetailsTheme.textSecondary,
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: pokemonDetailsTheme.action,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
  },
  retryButtonLabel: {
    color: pokemonDetailsTheme.white,
    fontSize: 15,
    fontWeight: "700",
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: pokemonDetailsTheme.error,
    marginBottom: 10,
  },
  errorCopy: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    color: pokemonDetailsTheme.errorMuted,
  },
});
